# Project: Proyecto1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Nodo.o ListaCircularDoble.o menu.o Archivotxt.o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.o
LINKOBJ  = Nodo.o ListaCircularDoble.o menu.o Archivotxt.o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lgdi32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Parqueadero.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Nodo.o: Nodo.cpp
	$(CPP) -c Nodo.cpp -o Nodo.o $(CXXFLAGS)

ListaCircularDoble.o: ListaCircularDoble.cpp
	$(CPP) -c ListaCircularDoble.cpp -o ListaCircularDoble.o $(CXXFLAGS)

menu.o: menu.cpp
	$(CPP) -c menu.cpp -o menu.o $(CXXFLAGS)

Archivotxt.o: Archivotxt.cpp
	$(CPP) -c Archivotxt.cpp -o Archivotxt.o $(CXXFLAGS)

../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.o: ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.cpp
	$(CPP) -c ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.cpp -o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/Manual.o $(CXXFLAGS)

../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.o: ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.cpp
	$(CPP) -c ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.cpp -o ../../../OneDrive/Attachments/Escritorio/CopiaProyecto/CODIGO/main.o $(CXXFLAGS)
